Put lasso on toolbar. Created way to switch off loading of filetree

diff --git a/bin/providentia b/bin/providentia
--- a/bin/providentia
+++ b/bin/providentia
@@ -31,7 +31,7 @@ IFS=$'\n\t'
 # An option followed by double colons '::' means that its argument is optional.
 # See `man getopt'.
 SHORT=uc:t:J:q:m:V
-LONG=usage,cores:,time:,jobname:,queue:,mem:,constraint:,help,version,debug,interactive,conf:,config:,config_dir:,section:,ghost_version:,cartopy_data_dir:,ghost_root:,nonghost_root:,exp_root:,offline,interactive,network:,species:,resolution:,start_date:,end_date:,experiments:,temporal_colocation:,spatial_colocation:,filter_species:,lower_bound:,upper_bound:,report_type:,report_summary:,report_stations:,report_title:,report_filename:,map_extent:,active_dashboard_plots:,plot_characteristics_filename:
+LONG=usage,cores:,time:,jobname:,queue:,mem:,constraint:,help,version,debug,interactive,conf:,config:,config_dir:,section:,ghost_version:,cartopy_data_dir:,ghost_root:,nonghost_root:,exp_root:,generate_file_tree,file_tree,gft,offline,interactive,network:,species:,resolution:,start_date:,end_date:,experiments:,temporal_colocation:,spatial_colocation:,filter_species:,lower_bound:,upper_bound:,report_type:,report_summary:,report_stations:,report_title:,report_filename:,map_extent:,active_dashboard_plots:,plot_characteristics_filename:
 
 # parse arguments
 PARSED=$(getopt --options ${SHORT} \
@@ -45,6 +45,21 @@ fi
 
 # reset SLURM_EXPORT_ENV so that things like srun & sbatch work out of the box
 export SLURM_EXPORT_ENV=ALL
+
+# get OS
+#Mac OS X platform        
+if [ "$(uname)" == "Darwin" ]; then
+    OS="Mac"        
+#GNU/Linux platform
+elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+    OS="Linux"
+# Windows platform
+elif [ "$(expr substr $(uname -s) 1 10)" == "Windows" ] || [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ] || [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
+    OS="Windows"
+else
+    echo "The OS cannot be detected. Exiting."
+    exit 1
+fi
 
 # update key arguments for job submission
 OTHEROPTS=""
@@ -123,8 +138,14 @@ fi
 # EXPORTPATH="/gpfs/home/bsc32/bsc32781/.conda/envs/myenv/lib/python3.9/site-packages"
 # export PYTHONPATH=${EXPORTPATH}:${PYTHONPATH}
 
-# get IP
-ip=$(hostname --ip-address)
+# get IP (different method for each OS)
+if [ "${OS}" == "Mac" ]; then
+    ip=${LOCAL_IP:-`ipconfig getifaddr en0`}
+elif [ "${OS}" == "Linux" ]; then
+    ip=$(hostname --ip-address)
+elif [ "${OS}" == "Windows" ]; then
+    ip=${LOCAL_IP:-`ipconfig.exe | grep -im1 'IPv4 Address' | cut -d ':' -f2`}
+fi
 
 # execution
 # CTE POWER 9
@@ -233,7 +254,7 @@ elif [ "${BSC_MACHINE}" == "nord3v2" ]; then
 
 # Hub
 elif [ "${ip}" == "84.88.185.48" ]; then
-    echo "Warning: running in the hub may make Providentia slower ..."
+    echo "Warning: running on the hub may make Providentia slower ..."
     eval "${load_command}"
     if $interactive; then
         echo "Starting interactive jupyter session."
@@ -245,7 +266,6 @@ elif [ "${ip}" == "84.88.185.48" ]; then
 
 # Local machines (Workstations, dust02 machine and personal laptops)
 else
-    echo "Warning: running in local machines may make Providentia slower ..."
     if $interactive; then
         echo "Starting interactive jupyter session."
         export PYTHONPATH=$(pwd):${PYTHONPATH}
